name: Run Tests and Display File Content

on: [push]

jobs:
  test-and-display:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest

      - name: Display file content
        run: |
          echo "Content of the requirements.txt file:"
          cat requirements.txt
